### ISSUE TITLE
Class description not work with `export`

### ISSUE THREAD

**Issue by gocreating** [jsdoc3/jsdoc#1137]
When I describe an export class

![image](https://cloud.githubusercontent.com/assets/5002343/12085320/c860b196-b2f9-11e5-8bcc-ab3359f45327.png)

nothing generates

![image](https://cloud.githubusercontent.com/assets/5002343/12085326/db6dc5a8-b2f9-11e5-9e4d-edd07f8cf60c.png)

When I cut the `export`

![image](https://cloud.githubusercontent.com/assets/5002343/12085329/e4e9f598-b2f9-11e5-9e7b-0fd247c4db5d.png)

It works fine

![image](https://cloud.githubusercontent.com/assets/5002343/12085335/f10a47c4-b2f9-11e5-830c-6deb7f222903.png)

How can I solve this problem?

**Comment by rozzzly** [comment]
It's even worse if you try `export default class MyClass { } `, and God forbid you have a @module annotation at the beginning of the file (separate doclet from the one above the class definition.

**Comment by zandaqo** [comment]
ES2015 is still a work in progress, guys, I believe you can follow it at #555 

In this particular case, I'd just recommend separating class description and exporting, it works for me in 3.4:
```javascript
/** */
class App {}

export default App;
```

**Comment by gocreating** [comment]
@rozzzly @zandaqo I will separate `export` and `class`. Thanks!

**Comment by nathanmarks** [comment]
@gocreating @rozzzly

It seems like something has been implemented regarding classes that basically hijacks the file. Not only that but it is intentional.

**Comment by nathanmarks** [comment]
@rozzzly I'm writing a personal plugin for my own docs (slightly opinionated) and part of it is normalizing some of the exports behaviour (cleaner multiple es6 exports with better `@module` support).

I imagine that I'll be able to separate some of the functionality to fix the class export issue with a plugin.

Personally i'm using babel 6 with no commonjs interop for my exports, which means that even my `default` exports are not synonymous with `module.exports()` and need to be accessed using `require().default` so my plugin is also designed to solve that issue for me by putting default exports on `exports.default`.

If the class functionality of hijacking the entire `@module` in scope is a design feature that will remain, I will 100% try and put a plugin together -- I'd rather be explicit about what classes represent entire modules via comments than have jsdoc automatically force that on me. Maybe @hegemonic can shed some light here

**Comment by nathanmarks** [comment]
@rozzzly here's a little demo of what I've got going so far:

Consider this code:
```js
/**
 * Some lib description
 *
 * @module my-lib
 */

/**
 * The plugin object.
 *
 * @type {Object}
 */
const libObject = {};

/**
 * Helper function
 */
function helper () {}

/**
 * Fighter function
 */
function fighter () {}

/**
 * Bazz is a pretty rad function
 */
export default function Bazz () {}

export { libObject, helper, fighter };

/**
 * Super awesome class!
 */
export class App {

}
```

You get 

![image](https://cloud.githubusercontent.com/assets/4420103/12570057/863e34b4-c3a2-11e5-81c9-35f3a4ed9e01.png)

**Comment by nathanmarks** [comment]
I've still gotta work out a few issues with it but I'll post a link here when I'm done

**Comment by nathanmarks** [comment]
@gocreating  @rozzzly 

I got `export default class App` working too.... by cheating with a `beforeParse` event hook using [a dirty regex](http://www.regexr.com/3clk5) search/replace on the source code.

I got pretty close to solving it in a cleaner way using the `visitNode` hook, maybe it should be fixed via PR though.

**Comment by rozzzly** [comment]
Awesome job @nathanmarks

**Comment by asnov** [comment]
Hi guys, any progress on this?

**Comment by Reinmar** [comment]
Bumping up. Plus, a DUP: https://github.com/jsdoc3/jsdoc/issues/1252.

**Comment by Reinmar** [comment]
I wrote down result of my research on current JSDoc's support for ES6 modules: https://github.com/jsdoc3/jsdoc/issues/555#issuecomment-245549805.

**Comment by hegemonic** [comment]
This is indeed a bug. The following example should work; instead, the class description ends up in a separate, misnamed doclet from the class' doclet:

```js
/** Class description */
export class Foo {
}
```

I'll investigate.

**Comment by hegemonic** [comment]
Fixed on master and releases/3.4. The fix will be included in JSDoc 3.4.2.

**Comment by englercj** [comment]
This is closed, but is still broken in v3.4.2. Without the hack mentioned in https://github.com/jsdoc3/jsdoc/issues/1137#issuecomment-174829004 it still is incorrect.

Here is what we are using in pixi to work around this issue, but this should be reopened because it is still active: https://github.com/pixijs/pixi.js/blob/dev/scripts/jsdoc-fix.js

**Comment by develar** [comment]
Is it going to be reopened? `JSDoc 3.4.3 (Thu, 10 Nov 2016 00:25:10 GMT)` is still affected.

**Comment by dpyro** [comment]
Can confirm that `JSDoc 3.4.3 (Thu, 10 Nov 2016 00:25:10 GMT)` still exhibits this behavior.

**Comment by hegemonic** [comment]
I made some additional fixes for ES2015 modules and classes on GitHub master. The additional fixes will be included in JSDoc 3.5.0.

If you are still seeing problems on GitHub master, please file a new issue.
