### ISSUE TITLE
Feature Request - Support/Plugin for ES7 Async/Await syntax

### ISSUE THREAD

**Issue by opvasger** [jsdoc3/jsdoc#1188]
I'm using Babel like many others, and AFAIK there's no way to parse async functions with jsdoc - correct?

Is this something I should perhaps write a plugin for, and if so, how would I go about doing that? Or does this perhaps already exist somewhere I haven't already looked?

great project btw!

**Comment by ORESoftware** [comment]
+1

**Comment by catalsdevelop** [comment]
i meet with same problems

**Comment by sabrinaluo** [comment]
+1

**Comment by jcowgar** [comment]
I just wrote a very generic/dumb jsdoc plugin that allows us to use jsdoc on code that includes async/await. It does so by stripping the async/await words from the source file. This module may get better, but will never be perfect. That said, it is working fine on my source docs right now.

I'm sure others will chime in and help make the regex better also.

Anyway, I **just** published it to npm, you can grab it https://www.npmjs.com/package/jsdoc-strip-async-await   ... this is just a tide-me-over async/await is officially supported.

**Comment by Icemic** [comment]
+1

**Comment by vasyas** [comment]
+1

**Comment by 285858315** [comment]
+1

**Comment by ejfrancis** [comment]
+1

**Comment by DataTables** [comment]
Is there any scope to sponsor features such as this?

**Comment by hegemonic** [comment]
JSDoc will support this feature sometime soonish after Espree, our JavaScript parser, supports it. The Espree work is being tracked in eslint/espree#287; looks like it's getting close.

**Comment by DataTables** [comment]
Awesome - thanks. I suppose more generally is there a way to donate or otherwise sponsor development on JSDoc? I get a lot of use from it (as I'm sure others do) is its only fair to contribute back. Unfortunately I don't have time to add code at the moment, but I'd like to help somehow and this is perhaps one way. I didn't find anything on the site or in this repo, so perhaps its not something that you or the other developers are interested in (absolutely understand!).

**Comment by leeyeh** [comment]
FYI, ES2017 support for espree landed in v3.2.0

**Comment by macdja38** [comment]
+1 As async/await is now fully supported in node.js as of 7.6

**Comment by damianobarbati** [comment]
any news on this?

**Comment by cula** [comment]
+1

**Comment by area73** [comment]
+1

**Comment by jerroydmoore** [comment]
+1

**Comment by jvanveen** [comment]
Does this make sense? 

https://github.com/jvanveen/jsdoc/commit/a789c902c56e7852ecff1825dc4f5d8fcd36a5ed

I fiddled a bit with the walker and updated espree to a version that supports async.

**Comment by larsgw** [comment]
+1

**Comment by LeeJim** [comment]
use jsdoc plugin - [jsdoc-babel](https://github.com/ctumolosus/jsdoc-babel)

**Comment by keithrz** [comment]
@jvanveen 's repo worked for me.  +1 to a jsdoc version with those changes

**Comment by zbraniecki** [comment]
@jvanveen - we use your branch in FluentDOM and encountered an error with the following code:

```javascript
if (1) {
  ctx = await ctx;
}
```

**Comment by jvanveen** [comment]
I'll look into it. Got the same issue.

**Comment by Fl4m3Ph03n1x** [comment]
Any news on this? Or do we still have to depend on plugins?

1. https://www.npmjs.com/package/jsdoc-strip-async-await
2. https://github.com/ctumolosus/jsdoc-babel

**Comment by jvanveen** [comment]
thanks for the reminder, will work on this after lunch 😀

**Comment by jvanveen** [comment]
@zbranlecki this worked for me, https://github.com/jvanveen/jsdoc/commit/ebc778a1fa6827c3f9570c318ea01fcc169a8348

**Comment by jvanveen** [comment]
Ok, made an attempt: https://github.com/jvanveen/jsdoc/commit/ebfb5ab7bfa9935e8a71430ae0cceac04849aca0

**Comment by jvanveen** [comment]
This may be a better approach: https://github.com/jvanveen/jsdoc/commit/3e913813c382b9da7a1ce81946f49cdcb6992544

A jsdoc template can check for a node's async property to indicate that it's an async function. Something like https://github.com/wearespindle/jsdoc-rtd/commit/c4a1265a8c37bfe23ffdb2a4cf6c9f1f8e22248c

**Comment by jvanveen** [comment]
![screenshot_20170620_170130](https://user-images.githubusercontent.com/213060/27340292-712d235c-55da-11e7-8d3c-7538e5581e8f.png)

**Comment by jeroenvollenbrock** [comment]
@jvanveen I ran into a lot of problems while trying to use your fork on es2015 classes with async method definitions. Method definitions have a subnode called value, on which the async property is added. This made the jsdoc-rtd template crash. I've added a finisher to the function and method visitor that adds the async property to the doclet instead, and updated the templateHelper to add async as method attribute. I've also made the code run on node4 again, as your commits broke this too. This avoids having to change your template and resolves the crashes. 
[jvanveen/jsdoc#1](https://github.com/jvanveen/jsdoc/pull/1)

**Comment by hegemonic** [comment]
Fixed on master. The fix will be included in JSDoc 3.5.0.

JSDoc now autodetects async functions. In addition, you can use the new `@async` tag in a virtual comment to indicate that a function is async.

Also, the default template identifies async functions in its output. Third-party templates may not yet support this feature.

**Comment by lll000111** [comment]
Unfortunately it still doesn't seem to work (3.5.5.): https://github.com/jsdoc3/jsdoc/issues/1442

**Comment by l3laze** [comment]
Trying to document async functions is still not working for me; v4.0.1.

**Comment by lll000111** [comment]
@hegemonic _(ping)_ Does this need to be reopened?
