### ISSUE TITLE
Use an actively maintained Markdown processor

### ISSUE THREAD

**Issue by hegemonic** [jsdoc3/jsdoc#1243]
We currently use [`marked`](https://www.npmjs.com/package/marked) to process Markdown. However, `marked` is not very actively maintained. It may be worth moving to a more actively maintained Markdown processor.

**Comment by alflanagan** [comment]
http://commonmark.org/
A fully specified markdown implementation, with unit tests, etc.

**Comment by hegemonic** [comment]
I'm planning to switch to [`markdown-it`](https://github.com/markdown-it/markdown-it), with the [`markdown-it-anchor` plugin](https://github.com/valeriangalliat/markdown-it-anchor) if heading IDs are enabled.

For JSDoc 3.6.0, we'll add `markdown-it` and use it by default, but `marked` will still be available. For JSDoc 3.7.0, `marked` will be removed.

**Comment by hegemonic** [comment]
Fixed on master. The fix will be included in JSDoc 3.6.0.

**Comment by alystair** [comment]
@hegemonic I just noticed `marked` is still appearing in `package.json` of the latest downloadable release. Probably good idea to update it?
