### ISSUE TITLE
ES6 module exporting ES6 class omits members

### ISSUE THREAD

**Issue by samskivert** [jsdoc3/jsdoc#1293]
The following class:

```javascript
/**
 * Test module.
 * @module foo
 */

/**
 * Test class.
 */
export class Foo {

  /**
   * Test method.
   */
  testMethod() {
  }
}
```

fails to emit documentation for `testMethod`. You can run `jsdoc foo.js` and see the result immediately.

Based on my investigations of why our docs broke, the salient problem is here in the --explain output:

```
    {
        "comment": "/**\n * Test class.\n */",
        "meta": {
            "range": [
                63,
                135
            ],
            "filename": "foo.js",
            "lineno": 9,
            "path": "/Users/mdb/research/jsdoc-es6-bug",
            "code": {
                "id": "astnode100000001",
                "name": "exports.Foo",
                "type": "ClassDeclaration"
            }
        },
        "classdesc": "Test class.",
        "name": "Foo",
        "longname": "module:foo.Foo",
        "kind": "class",
        "memberof": "module:foo",
        "scope": "static"
    },
```

Where `exports.Foo` appears, this seems to break things. When I make changes that cause that to be just `Foo`, things work.

[explain.txt](https://github.com/jsdoc3/jsdoc/files/587967/explain.txt)
[foo.js.txt](https://github.com/jsdoc3/jsdoc/files/587966/foo.js.txt)

**Comment by samskivert** [comment]
When the `export` is on the class declaration, an additional node is inserted into the explain output. With `export` we get:

```javascript
    {
        "comment": "/**\n * Test class.\n */",
        "meta": {
            "range": [
                63,
                135
            ],
            "filename": "foo.js",
            "lineno": 9,
            "path": "/Users/mdb/research/jsdoc-es6-bug",
            "code": {
                "id": "astnode100000001",
                "name": "exports.Foo",
                "type": "ClassDeclaration"
            }
        },
        "classdesc": "Test class.",
        "name": "Foo",
        "longname": "module:foo.Foo",
        "kind": "class",
        "memberof": "module:foo",
        "scope": "static"
    },
    {
        "comment": "",
        "meta": {
            "range": [
                70,
                135
            ],
            "filename": "foo.js",
            "lineno": 9,
            "path": "/Users/mdb/research/jsdoc-es6-bug",
            "code": {
                "id": "astnode100000002",
                "name": "Foo",
                "type": "ClassDeclaration",
                "paramnames": []
            }
        },
        "undocumented": true,
        "name": "Foo",
        "longname": "module:foo~Foo",
        "kind": "class",
        "scope": "inner",
        "memberof": "module:foo"
    },
```

and without the `export` (where `testMethod` documentation is generated properly) we get only:

```javascript
    {
        "comment": "/**\n * Test class.\n */",
        "meta": {
            "range": [
                63,
                128
            ],
            "filename": "foo.js",
            "lineno": 9,
            "path": "/Users/mdb/research/jsdoc-es6-bug",
            "code": {
                "id": "astnode100000001",
                "name": "Foo",
                "type": "ClassDeclaration",
                "paramnames": []
            }
        },
        "classdesc": "Test class.",
        "name": "Foo",
        "longname": "module:foo~Foo",
        "kind": "class",
        "scope": "inner",
        "memberof": "module:foo"
    },
```

**Comment by minexew** [comment]
Hi, is there any workaround for this?

**Comment by Native-Coder** [comment]
I'm having the same issue. Has anyone found a fix?

**Comment by minexew** [comment]
Not exactly a fix, but I worked around it by not marking classes as exported, instead exporting them "manually" at the end of the file.

**Comment by Native-Coder** [comment]
What do you mean manually? I use Classs Foo{} module.exports = Foo;

**Comment by minexew** [comment]
Oh, maybe you're having a different issue after all?

For, me
```
export class Foo {}
```
didn't work right, but
```
class Foo {}

export {Foo}
```
does.

**Comment by Native-Coder** [comment]
Very similar to what I do. I do

`class Foo{
//Members etc
}

module.exports = Foo;`

I actually found out how to get this working. Instead of staarting my module with 

```
/**
 * @module Foo
 * @exports Foo.Foo
*/
```

I do 


```
/** @module Foo */ <-- No exports

/**
 * @class
 * @memberof module:Foo  <-- instead, explicitly tell JSDOC what module the class is apart of
 */
class Bar{
    constructor(){
       /**
        * @member {String} module:Foo.Bar# <-- This generates the documentation correctly
        */
        this.String = 'blah';
    }
}

module.exports = Foo;

```

By using @member {Type} module:ModuleName.ClassName# we tell JSDOC explicitly what to do. It's a bit more time consuming. But at least it works..  ¯\_(ツ)_/¯

**Comment by sasha240100** [comment]
Any progress here?

**Comment by GEMI** [comment]
Ping!

**Comment by sasha240100** [comment]
plz fix

**Comment by hegemonic** [comment]
Fixed on master. The fix will be included in JSDoc 3.5.0.

**Comment by turnerhayes** [comment]
I'm still having this issue (`jsdoc@3.5.5`); the following file shows the constructor and the class, but all the virtual members are not appearing:




```
import { Record } from "immutable";

const schema = {
	userID: null,
	isAnonymous: true,
	isPresent: true,
	order: null,
	color: "",
	user: null
};

/**
 * Record representing a player in a particular game.
 *
 * @memberof client.records
 * @extends Immutable.Record
 */
class PlayerRecord extends Record(schema, "Player") {
	/**
	 * @param {object} args - the constructor arguments
	 * @param {string} args.userID - the ID of the user represented by this player
	 * @param {object} args.user - the user represented by this player. If specified,
	 *	this should contain an `id` key with the user ID. This parameter should be avoided;
	 *	use the `userID` parameter instead (the user data will not be stored in this record
	 *	anyway)
	 */
	constructor(args) {
		if (args.user && !args.userID) {
			args.userID = args.user.id;
			delete args.user;
		}

		super(args);
	}

	/**
	 * The ID of the user represented by this player
	 *
	 * @member {string} userID
	 */

	/**
	 * @member {boolean} isAnonymous - whether or not the user has a site account
	 */

	/**
	 * @member {boolean} isPresent - whether or not the player is present in the game
	 */

	/**
	 * @member {Number} order - the index (0-based) of where this player falls in the
	 *	turn order for the game
	 */

	/**
	 * @member {string} color - the color representing this player in the game
	 */
}

export default PlayerRecord;

```

**Comment by sankarsubramanian** [comment]
I am also still having the issue with jsdoc3.5.5.

Documentation is not generating for class members. It is generating only for constructor

export class Foo {
  /**
   * @description Test description
   */
  constructor() {
  }
 
 /**
  * @summary
  * Creates an Test Method
  * @desc 
  * Test Methd
  * @memberof Foo
  */
  test() {
 }
}

**Comment by samskivert** [comment]
You don't need @memberof and that might be messing things up. Does it work if you remove that?

**Comment by sankarsubramanian** [comment]
@samskivert Thanks! 
After adding the header string  It's working fine.

```
/** Class representing Foo. */
export class Foo {
  /**
   * @description Test description
   */
  constructor() {
  }
 
 /**
  * @summary
  * Creates an Test Method
  * @desc 
  * Test Method
  */
  test() {
 }
}
```

**Comment by SukantPal** [comment]
I'm still having this problem in 3.6.3:

```
/**
 * @memberof PIXI.brend
 */
export class BatchRenderer {}
```

I am forced to change it to:

```
/**
 * @memberof PIIX.brend
 */
class BatchRenderer {}

export { BatchRenderer}
```
