### ISSUE TITLE
JSDoc prettyprint's plain text markdown, adding random colors

### ISSUE THREAD

**Issue by lll000111** [jsdoc3/jsdoc#1361]
I have this JSDoc (excerpt) for a function:

```javascript
/**
 *....
 * Circle detection is not implemented, you simply get a
 * ```plain
 * RangeError: Maximum call stack size exceeded
 * ```
 * exception.
 *....
 */
```

This becomes what you see in the screenshot below, colorful text that is anything but "plain" (I also tried leaving out a code type string or using `text`, same results):

![screenshot-1](https://cloud.githubusercontent.com/assets/25476357/25780536/cb49f42a-3328-11e7-9846-97bd708bc8e5.png)

<br>

What is there to "pretty-print" in plain text?

**Comment by hegemonic** [comment]
This sounds like a bug in our [pretty-printing library](https://github.com/google/code-prettify). Please file a bug against that repo.

**Comment by lll000111** [comment]
Please reopen this ticket.

I filed a ticket for `prettyprint` and it seems the problem lies with JSDoc's usage, read

https://github.com/google/code-prettify/issues/495

**Comment by hegemonic** [comment]
Looks like we'll need to special-case the language `plain` and omit the `prettyprint` class in that case.

**Comment by hegemonic** [comment]
Fixed on master. The fix will be included in JSDoc 3.6.0.

**Comment by lll000111** [comment]
The issue is not fixed.

Here is my code:

```js
/**
 * (text removed) 
 *
 * ```
 * Uncaught DOMException: Failed to execute 'close' on 'WebSocket': The code must be either
 * 1000, or between 3000 and 4999. 1001 is neither.
 * ```
 * ```plain
 * Uncaught DOMException: Failed to execute 'close' on 'WebSocket': The code must be either
 * 1000, or between 3000 and 4999. 1001 is neither.
 * ```
 * ```txt
 * Uncaught DOMException: Failed to execute 'close' on 'WebSocket': The code must be either
 * 1000, or between 3000 and 4999. 1001 is neither.
 * ```
 * ```text
 * Uncaught DOMException: Failed to execute 'close' on 'WebSocket': The code must be either
 * 1000, or between 3000 and 4999. 1001 is neither.
 * ```
 *
 * (text removed) 
 *
 * @type {Object}
 * (text removed) 
 */
... // removed
```

Here is the result:
![unbenannt-1](https://user-images.githubusercontent.com/25476357/30595981-10df9cd0-9d53-11e7-8bda-3cd31faadf46.png)
