### ISSUE TITLE
Issue detecting comments with JSDoc (3.5.1)

### ISSUE THREAD

**Issue by ami-lpsc** [jsdoc3/jsdoc#1398]
Hi,
With JSDoc 3.5.1, the example below (for example) fails. The function is added in the documentation as a "Global" function and the separator comment (`/*-------------------------------------------------------------------------*/`) is taken as a description.

Best regards

```js
/*-------------------------------------------------------------------------*/

function _internal_done_fail(deferred, doneFunc, failFunc)
{
...
}

/*-------------------------------------------------------------------------*/
```

**Comment by vnglst** [comment]
Maybe the same issue or related: Normal comments (like so /* eslint: etc. */) are also seen as function documentation. See screenshots below.

![schermafdruk 2017-07-12 13 55 17](https://user-images.githubusercontent.com/3457693/28116588-fde6df1e-6709-11e7-8852-932500a54f6c.png)
![schermafdruk 2017-07-12 13 55 43](https://user-images.githubusercontent.com/3457693/28116589-fde833fa-6709-11e7-902d-cb007b1be4df.png)

**Comment by ami-lpsc** [comment]
Yes, this is the same issue.

**Comment by hegemonic** [comment]
Fixed on master and releases/3.5. The fix will be included in JSDoc 3.5.2.

**Comment by ami-lpsc** [comment]
Hi,
It doesn't fix the issue. Even if I replace "isValidJsdoc" by: 
function isValidJsdoc(commentSrc) { return false; }
I get the same issue (and the same document).

Moreover, in you code, you wrote:
return commentSrc && commentSrc.indexOf('/**') === 0 && commentSrc.indexOf('/***') !== 0;

It will return "true" if you have /**/.

I think that you have to write something like that:
return commentSrc && commentSrc.length > 4 && commentSrc.indexOf('/**') === 0 && commentSrc[3] !== '*'

Best regards

**Comment by lll000111** [comment]
@ami-lpsc Just an aside: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by hegemonic** [comment]
Ah, I see what happened—because your original comment wasn't formatted as a code block, GitHub was interpreting your comment delimiters as Markdown. As a result, I was testing something different than what you wanted me to test. Another good reason to use code blocks!

I'll investigate.

**Comment by hegemonic** [comment]
Okay, fixed for real this time. The fix will be included in JSDoc 3.5.3.
