### ISSUE TITLE
@inheritdoc fails when class C extends class B which implements interface A

### ISSUE THREAD

**Issue by myphysicslab** [jsdoc3/jsdoc#906]
Suppose that class C extends class B, and class B implements interface A.  Then class B shows the documentation inherited from interface A.  But class C does not.  Class C shows the method, but without the proper inherited documentation from interface A.

In the following example: GravityLaw extends AbstractSubject which implements Subject interface. The problem is the addObserver method in GravityLaw is lacking documentation.
The resulting documentation can be seen at:
http://www.myphysicslab.com/rmnp/test20150204a/out/index.html
Below is the code for this example.  Also available at 
http://www.myphysicslab.com/rmnp/test20150204a/test20150204a.js
Using JSDoc 3.4.0-dev (Thu, 22 Jan 2015 23:02:06 GMT)

```javascript
/** @classdesc Observes a {Subject}; is notified when something changes in the {Subject}.
@interface
*/
myphysicslab.lab.util.Observer = function() {};

/** @classdesc A {Subject} notifies its {Observer}s when something changes in the
{Subject}.
@interface
*/
myphysicslab.lab.util.Subject = function() {};

/** Adds the given {Observer} to the {Subject}'s list of {Observer}s, so that the
{Observer} will be notified of changes in this {Subject}.
@method
@param {!myphysicslab.lab.util.Observer} observer  the {Observer} to add to
        list of {Observer}s
*/
myphysicslab.lab.util.Subject.prototype.addObserver;

/** @classdesc A *reusable forwarding class* which implements the boilerplate code
for a {Subject}.
@constructor
@implements {myphysicslab.lab.util.Subject}
*/
myphysicslab.lab.util.AbstractSubject = function() {};

/** @inheritDoc */
myphysicslab.lab.util.AbstractSubject.prototype.addObserver = function(observer) {};

/** @classdesc A {ForceLaw} for a constant downward gravitational field.

@param {number} gravity
@constructor
@extends {myphysicslab.lab.util.AbstractSubject}
*/
myphysicslab.lab.model.GravityLaw = function(gravity, simList_opt) {
  /**
  * @type {number}
  * @private
  */
  this.gravity_ = gravity;
};

/** Returns the magnitude of the gravity force.
* @return {number} the magnitude of the gravity force
*/
myphysicslab.lab.model.GravityLaw.prototype.getGravity = function() {
  return this.gravity_;
};
```

**Comment by hegemonic** [comment]
Confirmed using this simplified test file:

```js
/**
 * A
 * @interface
 */
function A() {}

/**
 * Do a thing.
 */
A.prototype.doThing = function() {};

/**
 * B
 * @class
 * @implements {A}
 */
function B() {}

/** @inheritdoc */
B.prototype.doThing = function() {};

/**
 * C
 * @class
 * @extends {B}
 */
function C() {}
```

This happens because we do one pass to handle `@extends`, followed by a separate pass to handle `@implements`. I'm pretty sure we can get better results just by swapping the order of those two passes, but I need to poke around first and see if that causes any obvious breakage.

**Comment by hegemonic** [comment]
Okay, I think this one is fixed on master and releases/3.3. If you see any new weirdness as a result of the fix, please feel free to file a new issue.

**Comment by myphysicslab** [comment]
Issues #906 and #907 seem to be fixed (thanks!), but there is a new similar-but-different issue #909.

By the way, after updating the compiler I still get the same version string:

    [09:17:28 ~/Documents/Programming/jssimlab]$ jsdoc -v
    JSDoc 3.4.0-dev (Thu, 22 Jan 2015 23:02:06 GMT)

Shouldn't the build-time change at least?  I must have gotten the new version because #906 is working in the new version.

**Comment by hegemonic** [comment]
There's no "build" process for JSDoc--I manually increment the timestamp from time to time. So there are almost always several commits that show the same timestamp. Not ideal, but it narrows down the version that someone is using to a reasonably small number of commits, which is still useful.
